<?php
?>
<form>
    <h1>Willkommen auf der Startseite von Megs!</h1>
    <div class="kasten1">
            <h3>Registrieren</h3>
            <div class="form-group">
                <label for="exampleInputEmail1">Benutzername</label>
                <input type="username" class="form-control" id="exampleInputUsername" placeholder="Benutzername">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Email</label>
                <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Passwort</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Passwort">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Passwort wiederholen</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Passwort">
            </div>
            <div class="checkbox">
                <label>
                    <input type="checkbox"> Angaben speichern
                </label>
            </div>
            <button type="submit" class="btn btn-default">Registrieren</button>
    </div>
    

    <div class ="kasten2">
        <h3>Einloggen</h3>
        <div class="form-group">
            <label for="exampleInputEmail1">Email</label>
            <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Passwort</label>
            <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
        </div>
        <div class="checkbox">
            <label>
                <input type="checkbox"> Angaben speichern
            </label>
        </div>
        <button type="submit" class="btn btn-default">Einloggen</button>
    </div>
</form>
